# Generated by Django 4.2.8 on 2024-05-21 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="belong_dept",
        ),
        migrations.RemoveField(
            model_name="task",
            name="belong_dept",
        ),
        migrations.AddField(
            model_name="log",
            name="create_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_create_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="update_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_update_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="最后编辑人",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="create_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_create_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="update_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_update_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="最后编辑人",
            ),
        ),
    ]
